parameters:
    exchange_domain.office_bag.class: Exchange\DomainBundle\Service\OfficeBag
    exchange_domain.bank_bag.class: Exchange\DomainBundle\Service\BankBag
    exchange_domain.exchange_rate_bag.class: Exchange\DomainBundle\Service\ExchangeRateBag

services:
    exchange_domain.office_bag:
        class: %exchange_domain.office_bag.class%
        parent: "exchange_entity_bag.base_repository_bag"
        calls:
            - [initRepository, ["ExchangeDomainBundle:Office"]]

    exchange_domain.bank_bag:
        class: %exchange_domain.bank_bag.class%
        parent: "exchange_entity_bag.base_repository_bag"
        calls:
            - [initRepository, ["ExchangeDomainBundle:Bank"]]

    exchange_domain.exchange_rate_bag:
        class: %exchange_domain.exchange_rate_bag.class%
        parent: "exchange_entity_bag.base_repository_bag"
        calls:
            - [initRepository, ["ExchangeDomainBundle:ExchangeRate"]]