parameters:
#    exchange_domain.example.class: Exchange\DomainBundle\Example

services:
#    exchange_domain.example:
#        class: %exchange_domain.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
