parameters:
#    exchange_map.example.class: Exchange\MapBundle\Example

services:
#    exchange_map.example:
#        class: %exchange_map.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
